services:
  wallet-api:
    image: wallet-api
    build:
      context: .
      dockerfile: Wallet.RestAPI/Dockerfile
    ports:
      - "${API_PORT_HTTP}:8080"
      - "${API_PORT_HTTPS}:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnectionString=Server=db,1433;Database=WalletService;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "${DB_PORT}:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
